service: swagger-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1

functions:
  hello:
    handler: index.handler
    events: 
      - http: 
          path: /
          method: get
          cors: true
      - http: 
          path: /api-docs
          method: get
          cors: true
    environment:
      NODE_ENV: "Development"