openapi: 3.0.0
info:
  title: Swagger-API
  description: Swagger Api Tool For AWS API Gateway
  version: 1.0.0
  contact:
    email: ckorde@ccrn.com
servers:
  - url: '{schema}://{host}/{base_api}'
    description: base url for api
    variables:
      schema:
        default: https
      host: 
        default: a2a4d71ry9.execute-api.ap-south-1.amazonaws.com
      base_api: 
        default: dev
paths:
  "/users":
    post:
      tags:
      - users
      summary: Add new user
      description: ''
      operationId: addUser
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml      
      parameters: []
      requestBody:
        description: Add user request body
        required: true
        content:
          application/json:
            schema:
              $ref: "#definitions/AddUsers"
      responses:
        '200':
          description: Success
          schema:
            $ref: "#definitions/appResponse"
        default:
          description: Error
          schema:
            $ref: "#definitions/errorResponse"
    patch:
      tags:
      - users
      summary: Update an existing user details
      description: ''
      operationId: updateUsers
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters: []
      requestBody:
        description: Add user request body
        required: true
        content:
          application/json:
            schema:
              $ref: "#definitions/UpdateUsers"
      responses:
        '200':
          description: Success
          schema:
            $ref: "#definitions/appResponse"
        default:
          description: Error
          schema:
            $ref: "#definitions/errorResponse"
    get:
      tags:
      - users
      summary: Find users by ID
      description: Returns a single user from id
      operationId: getUserById
      produces:
      - application/json
      - application/xml      
      parameters:
      - name: id
        in: query
        description: users id
        required: true
        example: 1
      responses:
        200:
          description: Success
          schema:
            $ref: "#definitions/appResponse"
        default:
          description: Error
          schema:
            $ref: "#definitions/errorResponse"
    delete:
      tags:
      - users
      summary: Deletes a users
      description: ''
      operationId: deleteUsers
      produces:
      - application/json
      - application/xml
      parameters: []
      requestBody:
        description: Add user request body
        required: true
        content:
          application/json:
            schema:
              $ref: "#definitions/DeleteUser"
      responses:
        '200':
          description: Success
          schema:
            $ref: "#definitions/appResponse"
        default:
          description: Error
          schema:
            $ref: "#definitions/errorResponse"
  "/users-list":
    get:
      tags:
      - users-details
      summary: Find users by ID
      description: Returns a single user from id
      operationId: getUserById
      produces:
      - application/json
      - application/xml
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            $ref: "#definitions/appResponse"
        default:
          description: Error
          schema:
            $ref: "#definitions/errorResponse"
  "/token/{id}":
    get:
      tags:
      - test
      summary: Testing
      description: Testing
      servers:
      - url : https://a17fcma00b.execute-api.us-east-2.amazonaws.com/dev/lapi/v1/user
        description: Override base path for all operations with the /files path
      operationId: testOtherAPI
      produces:
      - application/json
      - application/xml      
      parameters:
      - name: id
        in: path
        description: users id
        required: true
      responses:
        200:
          description: Success
          schema:
            $ref: "#definitions/appResponse"
        default:
          description: Error
          schema:
            $ref: "#definitions/errorResponse"
definitions:
  appResponse:
    required: message
    properties:
      message:
        type: string
      code:
        type: number
  errorResponse:
    required: message
    properties:
      message:
        type: string
  AddUsers:
    type: object
    properties:
      id:
        type: string
      city:
        type: string
      name:
        type: string     
    example:
      id: "5"
      city: "Amravati"
      name: "Chetan Patil"
  UpdateUsers:
    type: object
    properties:
      id:
        type: integer
      updateKey:
        type: string
      updateValue:
        type: string
    example:
      id: "1"
      updateKey: "name"
      updateValue: "Chetan Patil Korde"
  DeleteUser:
    type: object
    properties:
      id:
        type: number
    example:
      id: "1"
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
